name: Terraform Deployment

on:
  push:
    branches:
      - feature**
      - main  # Adjust this to match your main branch name

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
          
      - name: Authenticate to Google Cloud Platform
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Terraform Init
        run: |
         terraform init -backend-config="bucket=aidana-gke-tfstate" -backend-config="prefix=tfstate/"

      - name: Terraform Plan
        run: |
          terraform plan 
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve tfplan
